config/routes.rb
Rails.application.routes.draw do
  get 'activities/index'

  devise_for :users, :path_prefix => 'd', controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations',
        passwords: "users/passwords",
        :omniauth_callbacks => "users/omniauth_callbacks"
      }

  authenticate :user do
    resources :recipes, only: [:new, :create, :edit, :update, :destroy]
  end

  resources :recipes do
    get :autocomplete_ingredient_name, :on => :collection
  end

  resources :users, only: [:show, :destroy]
  resources :recipes
  resources :ratings, only: :update
  resources :ingredients, only: :update
  resources :comments, only: :update
  resources :recipes do
    resources :comments
  end
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships,       only: [:create, :destroy]

  root 'static_pages#home'
  get 'about' => 'static_pages#about'
  get 'admin' => 'admin#admin_page'
  get 'contact', to: 'messages#new', as: 'contact'
  post 'contact', to: 'messages#create'
  get 'feed' => 'activities#index'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if !@yelp_response.blank?
      @yelp_response = Yelp.client.search('New York City', { term: 'Sangria Bars', limit: '6' })
    end
    if Recipe.ids.length != 0
      @randomRecipe = Recipe.find(Recipe.ids.sample)
    end
  end
  def about
  end
end

app/views/static_pages/about.html.erb
<div class="about_bg_wrapper">
    <div class="about_wrapper">
        <h1 class="about_title"> What is Sangria NYC? </h1>
        <div class="about_paragraphs">
            <p>
                We are a community of sangria loving, rooftop bar hopping,
                passionate and friendly New Yorkers. We put together this
                website to share our love of sangria.
            </p>
        </div>
    </div>
</div>

app/views/static_pages/home.html.erb
<div class="bg_wrapper">
  <div class="welcome_wrapper">
    <div class="welcome_content">
      <%= image_tag "sangria_welcome_image.jpg", size: "200x200", alt: "Edit Entry" %>
      <div class="welcome_text">
        <span class="welcome_title">WELCOME</span>
        <p>
           Peruse our selection of red, white or blended sangria recipe libraries or are you looking for some excitement?
           In that case, checkout the best rated sangria bars in the city.
           If you're feeling lucky you could spin the recipe roulette and learn how to make it yourself with a do-it-yourself video.
        </p>
      </div>
    </div>
  </div>
  <div class="create_recipe_wrapper">
    <div class="create_recipe">
      <%= link_to "Create A Recipe", new_recipe_path(@recipe) %>
    </div>
  </div>
  <div class="top_full_wrapper">

    <div class="pick_wine_wrapper">
      <div class="pick_wine">
        <div href="javascript:void(0)">Pick your wine!</div>
      </div>
    </div>

    <ul class="featured_recipes">
        <li class="featured_recipe_left">
          <a><%= link_to image_tag("red_sangria_trans_bg.png", size: "200x200", alt: "Edit Entry"), recipes_path(:flavor=>"red") %></a></li>
        <li class="featured_recipe_middle">
          <a><%= link_to image_tag("white_sangria_trans_bg.png", size: "200x200", alt: "Edit Entry"), recipes_path(:flavor=>"white") %></a></li>
        <li class="featured_recipe_right">
          <a><%= link_to image_tag("blue_sangria_trans_bg.png", size: "200x200", alt: "Edit Entry"), recipes_path(:flavor=>"exotic") %></a></li>
    </ul>
  </div>

  <div class="bottom_full_wrapper">
    <div class="bottom_content">
      <% if !@yelp_response.blank? %>
        <div class="top_bars">
          <div class="yelp_title">Top Sangria Bars in NYC!</div>
          <div class="yelp_logo"><%= image_tag "yelp-logo.png", alt: "Edit Entry" %></div>
          <ol class="yelp_businesses">
            <% @yelp_response.businesses.each do | business | %>
              <li class="businesses_container">
                <a href=<%= business.url %>>
                  <span class="business_container_link"></span>
                <%= business.name %><br>
                <%= image_tag(business.rating_img_url_small) %><br>
                <%= business.location.neighborhoods != nil ? business.location.neighborhoods.first : "" %>
                </a>
              </li>
            <% end %>
          </ol>
        </div>
      <% end %>
      <div class="recipe_roulette">
          <ul>
            <%=
              if Recipe.ids.length != 0
                link_to image_tag("recipe_roulette_color.png"), recipe_path(@randomRecipe.id)
              else
                link_to image_tag("recipe_roulette_color.png"), "#"
              end
            %>
          </ul>
      </div>
      <div class="youtube_video">
        <iframe
        src="https://www.youtube.com/embed/M7qjo30yJYQ"
        frameborder="0" allowfullscreen>
        </iframe>
      </div>
    </div>
  </div>
</div>