config/routes.rb
Rails.application.routes.draw do
  get 'activities/index'

  devise_for :users, :path_prefix => 'd', controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations',
        passwords: "users/passwords",
        :omniauth_callbacks => "users/omniauth_callbacks"
      }

  authenticate :user do
    resources :recipes, only: [:new, :create, :edit, :update, :destroy]
  end

  resources :recipes do
    get :autocomplete_ingredient_name, :on => :collection
  end

  resources :users, only: [:show, :destroy]
  resources :recipes
  resources :ratings, only: :update
  resources :ingredients, only: :update
  resources :comments, only: :update
  resources :recipes do
    resources :comments
  end
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships,       only: [:create, :destroy]

  root 'static_pages#home'
  get 'about' => 'static_pages#about'
  get 'admin' => 'admin#admin_page'
  get 'contact', to: 'messages#new', as: 'contact'
  post 'contact', to: 'messages#create'
  get 'feed' => 'activities#index'

end

app/views/admin/admin_page.html.erb
<h1>Admin Page</h1>

<table>
    <thead>
        <th>Recipe id</th>
        <th>Recipe Name</th>
        <th>Image</th>
        <th>Rating</th>
        <th>Author</th>
    </thead>
    <tbody>
<% @recipes.each do |recipe| %>
    <tr>
        <td><%= recipe.id %></td>
        <td><%= recipe.name %></td>
        <td><%= image_tag(recipe.recipe_image.url, width: "64") %></td>
        <td><%= recipe.average_rating %></td>
        <td><%= recipe.author %></td>
        <td><%#= link_to "edit", edit_recipe_path(recipe)%></td>
        <td><%#= link_to "delete", recipe_path(recipe), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
<% end %>
    </tbody>
</table>
<table>
    <thead>
        <th>User id</th>
        <th>Username</th>
        <th>Email</th>
        <th>Image</th>
        <th>Admin?</th>
    </thead>
    <tbody>
<% @users.each do |user| %>
    <tr>
        <td><%= user.id %></td>
        <td><%= user.user_name %></td>
        <td><%= image_tag(user.avatar, width: "64") %></td>
        <td><%= user.admin %></td>
        <td><%#= link_to "edit", edit_user_path(user)%></td>
        <td><%#= link_to "delete", admin_path(user), :method => :delete %></td>
    </tr>
<% end %>
    </tbody>
</table>