config/routes.rb
Rails.application.routes.draw do
  get 'activities/index'

  devise_for :users, :path_prefix => 'd', controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations',
        passwords: "users/passwords",
        :omniauth_callbacks => "users/omniauth_callbacks"
      }

  authenticate :user do
    resources :recipes, only: [:new, :create, :edit, :update, :destroy]
  end

  resources :recipes do
    get :autocomplete_ingredient_name, :on => :collection
  end

  resources :users, only: [:show, :destroy]
  resources :recipes
  resources :ratings, only: :update
  resources :ingredients, only: :update
  resources :comments, only: :update
  resources :recipes do
    resources :comments
  end
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships,       only: [:create, :destroy]

  root 'static_pages#home'
  get 'about' => 'static_pages#about'
  get 'admin' => 'admin#admin_page'
  get 'contact', to: 'messages#new', as: 'contact'
  post 'contact', to: 'messages#create'
  get 'feed' => 'activities#index'

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  include PublicActivity::Common
  # tracked owner: ->(controller, model) { controller && controller.current_user }
  has_many :ingredients, dependent: :destroy
  accepts_nested_attributes_for :ingredients, allow_destroy: true
  has_many :ratings, dependent: :destroy
  belongs_to :user
  has_many :comments, dependent: :destroy
  accepts_nested_attributes_for :comments, allow_destroy: true
  mount_uploader :recipe_image, RecipeImageUploader
  validates_presence_of :instructions, :servings
  validates :name, presence: true, length: { minimum: 5, maximum: 50 }
  validates :user_id, presence: true
  validate :recipe_image_size

  def average_rating
    if ratings.size > 1
      (ratings.sum(:score) / (ratings.size - 1))
    else
      nil
    end
  end

  filterrific :default_filter_params => { :sorted_by => 'name_desc' },
                :available_filters => %w[
                  sorted_by
                  search_query
                  search_query_ingredients
                  with_flavor_wine
                ]

  scope :search_query, lambda { |query|
    return nil  if query.blank?
    terms = query.downcase.split(/\s+/)
    terms = terms.map { |e|
      ('%' + e.gsub('*', '%') + '%').gsub(/%+/, '%')
    }
    num_or_conditions = 1
    where(
      terms.map { |term|
        or_clauses = [
          "LOWER(recipes.name) LIKE ?"
        ].join(' OR ')
        "(#{ or_clauses })"
      }.join(' AND '),
      *terms.map { |e| [e] * num_or_conditions }.flatten
    )
  }

  scope :search_query_ingredients, lambda { |query|
    return nil  if query.blank?
    terms = query.downcase.split(/\s+/)
    terms = terms.map { |e|
      ('%' + e.gsub('*', '%') + '%').gsub(/%+/, '%')
    }
    where(
      terms.map { |term|
        or_clauses = [
          "LOWER(ingredients.name) LIKE ?"
        ].join(' OR ')
        "(#{ or_clauses })"
      }.join(' AND '),
      *terms.map { |e| [e] }.flatten
    ).joins(:ingredients)
  }

  scope :sorted_by, lambda { |sort_option|
    # extract the sort direction from the param value.
    direction = (sort_option =~ /desc$/) ? 'desc' : 'asc'
    case sort_option.to_s
    when /^name_/
      order("LOWER(recipes.name) #{ direction }")
    when /^author_/
      order("LOWER(recipes.author) #{ direction }")
    when /^created_at_/
      order("LOWER(recipes.created_at) #{ direction }")
    when /^avg_rating_/
      order("LOWER(recipes.avg_rating) #{ direction }")
    else
      raise(ArgumentError, "Invalid sort option: #{ sort_option.inspect }")
    end
  }

  scope :with_flavor_wine, lambda { |flavors|
    where(:flavor => [*flavors])
  }

  def self.options_for_sorted_by
    [
      ['Name (a-z)', 'name_asc'],
      ['Author (a-z)', 'author_asc'],
      ['Date Created (Newest First)', 'created_at_desc'],
      ['Rating (Highest first)', 'avg_rating_desc']    ]
  end

  private

  def recipe_image_size
    if recipe_image.size > 5.megabytes
      errors.add(:recipe_image, "should be less than 5MB")
    end
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_filter :check_logged_in, only: [:create, :edit, :update, :destroy]
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]
  helper_method :sort_column, :sort_direction
  respond_to :html, :js
  autocomplete :ingredient, :name, full: true, unique: true
  def index
    if params[:flavor]
      recipeFlavor = params[:flavor]
      if recipeFlavor != "exotic"
        @title = "#{recipeFlavor.capitalize} Wine Recipes"
      else
        @title = "Exotic Recipes"
      end
      @recipes = Recipe.where(:flavor => params[:flavor])
    else
      @title = "All Recipes"
      @recipes = Recipe.all
    end
    @filterrific = initialize_filterrific(
      @recipes,
      params[:filterrific],
      :select_options => {
        sorted_by: @recipes.options_for_sorted_by,
        with_flavor_wine: {'Red': 'red', 'White': 'white', 'Exotic': 'exotic'}
      },
      :persistence_id => false,
    ) or return
    @recipes = @filterrific.find.page(params[:page])
    @recipes = @recipes.paginate(page: params[:page], :per_page => 6)
    respond_to do |format|
      format.html
      format.js
    end
    rescue ActiveRecord::RecordNotFound => e
    # There is an issue with the persisted param_set. Reset it.
    puts "Had to reset filterrific params: #{ e.message }"
    redirect_to(reset_filterrific_url(format: :html)) and return
  end

  def new
    @recipe = current_user.recipes.new
    @recipe.ingredients.build
    @counter = 0
  end

  def create
    @recipe = current_user.recipes.new(recipe_params)
    @recipe.author = current_user.user_name
    respond_to do |format|
      if @recipe.save
        @recipe.create_activity :create, owner: current_user
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :index, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @recipes_sort = Recipe.includes(:comments).order("comments.created_at desc").find(params[:id])
    @ingredients = Ingredient.where( :recipe_id => @recipe.id )
    if current_user
      @rating = Rating.where(recipe_id: @recipe.id, user_id: current_user.id).first
      unless @rating
        @rating = Rating.create(recipe_id: @recipe.id, user_id: current_user.id, score: nil)
      end
    end
  end

  def edit
    @counter = 0
  end

  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        @recipe.create_activity :update, owner: current_user
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :index, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully removed.' }
      format.json { head :no_content }
    end
  end

  def visibility_auth(curr_user, comment_id)
    !curr_user.blank? && (curr_user.id == comment_id)
  end
  helper_method :visibility_auth

  private

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:name, :description, :instructions, :author, :servings, :recipe_image, :user_id, :flavor, :avg_rating, :source, ingredients_attributes: [:name, :quantity, :measurement, :category, :_destroy, :id, :recipe_id])
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
  def xeditable? object = nil
    true # Or something like current_user.xeditable?
  end
end

app/views/recipes/_form.html.erb
<div class="recipe_form_wrapper">
  <div class="recipe_form_content">
    <div class="recipe_form_title"> <%= title %> </div>
    <%= bootstrap_form_for(@recipe) do |f| %>
      <%= f.text_field :name, autofocus: true, placeholder: "What's the name of your recipe?"%>
      <%= f.text_area :description, size: "25x2", placeholder: "What makes it special?"%>
      <%= f.text_area :instructions, size: "25x3", placeholder: "How do you make it?"%>
      <%= f.nested_fields_for :ingredients do |ingredient_field| %>
        <%= ingredient_field.remove_nested_fields_link do
            !!@counter && (@counter <= 0) ? @counter += 1 : ("Remove Ingredient")
        end %>
        <%= ingredient_field.hidden_field :recipe_id, :value => @recipe.id%>
        <%= ingredient_field.select :category,[ [ "Wine", "wine" ], [ "Liqour", "liqour" ], [ "Garnish", "garnish" ], [ "Other", "other"] ], label: "Ingredient Category"%>
        <%= ingredient_field.text_field :name, label: "Ingredient Name"%>
        <%= ingredient_field.number_field :quantity%>
        <%= ingredient_field.select :measurement, [ [ "Ounce(s)", "oz(s)" ], [ "Bottle(s)", "bottle(s)"], [ "Litre(s)", "litre(s)" ], [ "Millilitre(s)", "ml(s)" ], [ "Other", "other"] ], { label: "Measurement Amount", :include_blank => true}, { :onchange => "other_measurement()" } %>
        <%#= ingredient_field.text_field :measurement, hide_label: true, style: 'display: none;',  class: "other_field"%>
      <% end %>
      <%= f.add_nested_fields_link :ingredients, 'Add another ingredient', class: 'btn btn-primary', role: 'button'%>
      <%= f.select :servings, ["2-6", "6-12", "12+"], placeholder: "How many people does it serve?"%>

      <%= f.select :flavor, [ [ "Red Wine", "red" ], [ "White Wine", "white" ], [ "Exotic", "exotic" ] ], placeholder: "What is it made with?"%>
      <%= f.hidden_field :avg_rating, :value => nil %>
      <%= f.file_field :recipe_image, placeholder: "Recipe Image"%>
      <%= f.submit :class => "btn btn-default" %>
    <% end %>
  </div>
</div>
<script>
  function other_measurement() {
      $.each(document.getElementsByClassName('other_field'), function( i, v ) {
        if (document.getElementById('recipe_ingredients_attributes_0_measurement').value == 'other') {
          document.getElementsByClassName('other_field')[i].style.display = 'block';
        } else {
          document.getElementsByClassName('other_field')[i].style.display = 'none';
        }
      })
  }
</script>

app/views/recipes/_list.html.erb
<div id="filterrific_results">
  <div class="recipe_index_wrapper">
      <div class="recipe_index_content">
          <div class="paginate_wrapper"><%= will_paginate %></div>
          <div class="recipe_index_recipe_list">
              <% @recipes.each do |recipe| %>
                  <ul class="recipe_list">
                      <%= link_to recipe_path(recipe.id) do %>
                        <li><%= image_tag recipe.recipe_image.url %></li>
                        <li><span class="index_name"><%= recipe.name %></span></li>
                      <% end %>
                      <%= link_to recipe.user.user_name, user_path(recipe.user.id) %>
                      <li><span class="index_rating"><div data-score=<%= recipe.avg_rating %> class="star"></div></span></li>
                  </ul>
              <% end %>
          </div>
      </div>
      <div class="paginate_wrapper">
          <%= will_paginate %>
      </div>
  </div>
</div>
<script>
  $('.star').raty({
    score: function() {
      return $(this).attr('data-score');
    },
    readOnly: true,
    path: '/assets'
  });
</script>

app/views/recipes/edit.html.erb
<div class="recipe_bg">
    <div class="recipe_wrapper">
      <%= render partial: "form", locals: {title: "Edit Recipe"} %>
    </div>
</div>

app/views/recipes/index.html.erb
<div class="recipe_index_wrapper">
    <div class="recipe_index_content">

      <% if !@flavor %>
        <span class="recipe_index_title"><%= @title %></span><br>
      <% end %>
      <div class='menu_container'>
          <%= form_for_filterrific @filterrific, html: { autocomplete: "off" } do |f| %>
          <div class='filter_sort_menu'>
            <div class="sort_by">Sort by <%= f.select(:sorted_by, @filterrific.select_options[:sorted_by]) %></div>
            <div class="filter_by">Filter by <%= f.select(:with_flavor_wine, @filterrific.select_options[:with_flavor_wine], { include_blank: '- Any -' }, class: 'select_change') %></div>
            <div><%= link_to('Reset filters', reset_filterrific_url) %></div>
          </div>
          <div class='search_menu'>
            <div id="name_search">
              <div class='search_by'>Recipe name <%= f.text_field(:search_query, class: 'filterrific-periodically-observed') %></div>
              <button onclick='toggleSearchTo("ingredients", event)'>Search by ingredient</button>
            </div>

            <div style="display:none;" id="ingredient_search">
              <!-- <div class='search_by'>Ingredient name<%#= f.text_field(:search_query_ingredients, class: 'filterrific-periodically-observed') %></div> -->
              <div class='search_by'>Ingredient name<%= f.autocomplete_field(:search_query_ingredients, autocomplete_ingredient_name_recipes_path, class: 'filterrific-periodically-observed') %></div>
              <button onclick='toggleSearchTo("name", event)'>Search by recipe</button>
            </div>
          </div>
          <% end %>
      </div>
      <%= render_filterrific_spinner %>

      <%= render(partial: 'recipes/list', locals: {recipes: @recipes}) %>

</div>

<script>
  function capitalize(string) {
    return string.charAt(0).toUpperCase() + string.slice(1);
  }
  var search_details = [
    {
      switchTo: "ingredients",
      show_field: "ingredient_search",
      hide_field: "name_search"
    },
    {
      switchTo: "name",
      show_field: "name_search",
      hide_field: "ingredient_search"
    }
  ]
  function toggleSearchTo(showElement, e) {
    e.preventDefault();
    for (var i=0;i<search_details.length;i++) {
      if (showElement == search_details[i].switchTo) {
        document.getElementById(search_details[i].show_field).style.display = 'block';
        $('.filterrific-periodically-observed').val(function() { return this.defaultValue; });
        document.getElementById(search_details[i].hide_field).style.display = 'none';
      }
    }
  }

  $('.select_change').change(function(){
    var select_value = capitalize( $(this).val() )
    $('.recipe_index_title').text((select_value == 'Exotic') ? (select_value + ' Recipes') : (select_value == 'White' || select_value == 'Red') ? (select_value + ' Wine Recipes') : 'All Wine Recipes');
  });
</script>

app/views/recipes/index.html_admin.erb
<h1>Recipes#index</h1>

<table>
    <thead>
        <th>ID</th>
        <th>Author</th>
        <th>Instructions</th>
    </thead>
    <tbody>
<% @recipes.each do |recipe| %>
    <tr>
        <td><%= recipe.id %></td>
        <td><%= recipe.author %></td>
        <td><%= recipe.instructions %></td>
        <td><%= link_to "edit", edit_recipe_path(recipe)%></td>
        <td><%= link_to "delete", recipe_path(recipe), method: :delete, data: { confirm: 'Are you sure?' }%></td>
    </tr>
<% end %>
    </tbody>
</table>

app/views/recipes/index.js.erb
<% js = escape_javascript(
  render(partial: 'recipes/list', locals: { recipes: @recipes, flavor: @flavor })
) %>
$("#filterrific_results").html("<%= js %>");

app/views/recipes/new.html.erb
<div class="recipe_bg">
    <div class="recipe_wrapper">
      <%= render partial: "form", locals: {title: "Create New Recipe"} %>
        <%#= render "form" %>
    </div>
</div>

app/views/recipes/show.html.erb
<div class="recipe_show_wrapper">
  <div class="recipe_show_content">

    <div class="recipe_show_heading">
      <div class="recipe_show_image_wrapper">
        <%= image_tag @recipe.recipe_image.url, :id => 'myImg', alt: @recipe.name, class: "img-responsive"%>
        <div id="photoModal" class="modal">
          <img class="modal-content" id="img01">
          <div id="caption"></div>
        </div>
      </div>

      <div class="recipe_show_title_name"><%= visibility_auth(current_user, @recipe.user_id) ? (editable @recipe, :name) : @recipe.name %></div>

      <div class="recipe_show_author_date">
        <span class="recipe_show_author_name"><%= link_to @recipe.user.user_name, user_path(@recipe.user.id) %></span>
        <span class="date_slashes"> // </span>
        <span class="recipe_show_publish_date"><%= @recipe.created_at.strftime("%B %e, %Y") %></span>
      </div>

      <div class='recipe_rating'>
        <p>Averate rating</p>
        <div id="star"></div>
        <% if current_user && current_user != @recipe.user%>
          <p>Your rating</p>
          <div id="user_star"></div>
        <% elsif !current_user %>
          Please <%= link_to "login", new_user_session_path %> or <%= link_to "create", new_user_registration_path %> an account to rate this recipe.
        <% end %>
      </div>

      <div class='recipe_management'>
        <% if current_user && (@recipe.user.user_name == current_user.user_name || current_user.admin) %>
          <li><%= button_to "edit", edit_recipe_path(@recipe), :method => :get %></li>
          <li><%= button_to "delete", recipe_path(@recipe), method: :delete, data: { confirm: 'Are you sure?' } %></li>
        <% end %>
      </div>
    </div>

    <div class="bottom_container">
      <div class="align_left">
        <ul class="recipe_details">
          <li class="recipe_description">
            <span class="recipe_show_title">Description: </span><%= visibility_auth(current_user, @recipe.user_id) ? (editable @recipe, :description) : @recipe.description %>
          </li>
          <br>
          <li class="recipe_instructions">
            <span class="recipe_show_title">Instructions: </span><%= visibility_auth(current_user, @recipe.user_id) ? (editable @recipe, :instructions) : @recipe.instructions %>
          </li>
          <br>
          <li class="recipe_servings">
            <span class="recipe_show_title">Servings: </span><%= visibility_auth(current_user, @recipe.user_id) ? (editable @recipe, :servings) : @recipe.servings %>
          </li>
          <br>
          <% if @recipe.source %>
            <li class="recipe_source">
              <span class="recipe_show_title">Recipe Source: </span><%= visibility_auth(current_user, @recipe.user_id) ? (editable @recipe, :source) : (link_to "Source Website", @recipe.source) %>
            </li>
            <br>
          <% end %>
          <li class='ingredient_container'><span class="recipe_show_title">Ingredients: </span><br>
            <% @ingredients.each_with_index do |ingredient, index| %>
              <div class= <%= index > 1 ? "hide_add_ingredients" : "" %> >
                <ul>
                  <li><span class="ingred_title">Category: </span><%= visibility_auth(current_user, @recipe.user_id) ? (editable ingredient, :category) : ingredient.category %></li>
                  <br>
                  <li><span class="ingred_title">Name: </span><%= visibility_auth(current_user, @recipe.user_id) ? (editable ingredient, :name) : ingredient.name %></li>
                  <br>
                  <li><span class="ingred_title">Quantity: </span><%= visibility_auth(current_user, @recipe.user_id) ? (editable ingredient, :quantity) : number_with_precision(ingredient.quantity, precision: 2, strip_insignificant_zeros: true)%></li>
                  <li><span class="ingred_title"></span><%= visibility_auth(current_user, @recipe.user_id) ? (editable ingredient, :measurement) : ingredient.measurement %></li>
                </ul>
              </div>
            <% end %>
            <% if @ingredients.length > 2 %>
            <a id="ingredReplaceOnClick" onclick="showIngredients()">Show more ingredients</a>
            <% end %>
          </li>
        <ul>
      </div>

      <div class="align_right">
        <div class="recipe_comments_container panel panel-default">
          <div class="recipe_comments">
            <div class="comment_form_container">
              <%= render 'comments/form' %>
            </div>
            <%= @recipes_sort.comments.length > 0 ? (render @recipes_sort.comments) : "There are no comments for this recipe." %>
            <% if @recipes_sort.comments.length > 2 %>
              <a id="commentReplaceOnClick" onclick="showComments()">Show more comments</a>
            <% end %>
          </div>
        </div>
      </div>
      <div class='clear'></div>
    </div>

    <script>
      //Ability to quick edit using jquery and ajax
      $.fn.editable.defaults.mode = 'inline'
      $(document).ready(function() {
        $('.editable').editable({
          showbuttons:false,
          onblur: "submit",
          ajaxOptions: {
            type: "PUT",
            dataType: "json"
          },
          //Makes text in input highlighted
        }).on('shown', function(ev, editable) {
            setTimeout(function() {
                editable.input.$input.select();
            },0);
        });
      })
      $('[title]').attr('title','click to edit');
      $("body").tooltip({
          selector: '.editable',
          placement: 'right'
      }, "option", "content", "Show Post - test");


      // close modal if clicked or touch event is triggered outside of photo
        var modal = document.getElementById('photoModal');
        var flag = false;

        $('#photoModal').bind('touchstart click', function(event){
          if (!flag) {
            flag = true;
            setTimeout(function(){ flag = false; }, 100);
              if (event.target == modal) {
                  modal.style.display = "none";
              }
          }
          return false
        });

        // Get the image and insert it inside the modal - use its "alt" text as a caption
        var img = document.getElementById('myImg');
        var modalImg = document.getElementById("img01");
        var captionText = document.getElementById("caption");
        img.onclick = function(){
          modal.style.display = "block";
          modalImg.src = this.src;
          captionText.innerHTML = this.alt;
        }
        $('#star').raty({
          readOnly: true,
          score: <%= @recipe.avg_rating ? @recipe.avg_rating : 0 %>,
          path: '/assets'
        });
        <% if current_user %>
          $('#user_star').raty({
            score: <%= @rating.score ? @rating.score : 0 %>,
            path: '/assets',
            click: function(score, evt) {
              $.ajax({
                url: '/ratings/' + <%= @rating.id %>,
                type: 'PATCH',
                data: { score: score }
              });
            }
          });
        <% end %>
        function showIngredients() {
          linkElement = document.getElementById("ingredReplaceOnClick")
          linkElement.innerHTML != "Hide ingredients" ? linkElement.innerHTML = "Hide ingredients" : linkElement.innerHTML = "Show more ingredients"
          $( ".hide_add_ingredients" ).toggle();
        }
        function showComments() {
          linkElement = document.getElementById("commentReplaceOnClick")
          linkElement.innerHTML != "Hide comments" ? linkElement.innerHTML = "Hide comments" : linkElement.innerHTML = "Show more comments"
          $( ".hide_add_comments" ).toggle();
        }
    </script>
    <style>
      .tooltip{
        font-size:9pt;
        font-family: 'Alegreya Sans SC', sans-serif;
      }
    </style>
  </div>
</div>